version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: brackets/nginx:latest
    ports:
     - "${DOCKER_APP_PORT:-80}:80"
    volumes:
     - ./public/:/var/www/html/public:delegated
    networks:
     - harbornet
  php:
    build:
      context: ./docker/php/${DOCKER_PHP_VERSION:-7.4}
      dockerfile: Dockerfile
    image: brackets/php:${DOCKER_PHP_VERSION:-7.4}
    environment:
      APP_ENV: "${APP_ENV:-local}"
      XDEBUG_HOST: "${XDEBUG_HOST:-host.docker.internal}"
      DOCKER_PHP_XDEBUG: "${DOCKER_PHP_XDEBUG:-off}"
      HARBOR_USER_UID: "${HARBOR_USER_UID:-1000}"
      TERMINAL_EMULATOR: "${DOCKER_TERMINAL_EMULATOR:-JetBrains-JediTerm}"
    volumes:
     - .:/var/www/html:delegated
     - ${DOCKER_SSH_PATH:-./docker/php/ssh}:/root/.ssh:delegated
     - ${DOCKER_SSH_PATH:-./docker/php/ssh}:/home/harbor/.ssh:delegated
     - psyhistoryroot:/root/.config
     - psyhistoryharbor:/home/harbor/.config
     - nodemodules:/var/www/html/node_modules
     - composercache:/home/harbor/.composer/cache
    networks:
     - harbornet
  pgsql:
    image: postgres:${DOCKER_POSTGRES_VERSION:-11}
    ports:
     - "${DOCKER_PGSQL_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-homestead}"
      POSTGRES_USER: "${DB_USERNAME:-homestead}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      PGPASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
     - pgsqldata:/var/lib/postgresql/data
     - ./docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
     - ./docker/pgsql/export:/export:delegated
     - ./docker/pgsql/import:/import:cached
    networks:
     - harbornet
  testing:
    image: postgres:${DOCKER_POSTGRES_VERSION:-11}
    ports:
     - "${DOCKER_PGSQL_TEST_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-homestead}"
      POSTGRES_USER: "${DB_USERNAME:-homestead}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      PGPASSWORD: "${DB_PASSWORD:-secret}"
    user: postgres
    volumes:
     - pgsqldatatest:/var/lib/postgresql/data:delegated
#     - ${DOCKER_PGSQL_TEST_DIR}:/var/lib/postgresql/data:delegated # uncomment to use dir as a filesystem
     - ./docker/testing/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    networks:
     - harbornet
  node:
    build:
      context: ./docker/node/${DOCKER_NODE_VERSION:-12}
      dockerfile: Dockerfile
      args:
        uid: "${HARBOR_USER_UID:-1000}"
        gid: "${HARBOR_USER_GID:-1000}"
    image: brackets/node:${DOCKER_NODE_VERSION:-12}
    user: node
    volumes:
     - .:/var/www/html:delegated
     - ./public:/var/www/html/public
     - vendor:/var/www/html/vendor
    networks:
     - harbornet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - harbornet
networks:
  harbornet:
    driver: "bridge"
volumes:
  pgsqldata:
    driver: "local"
  pgsqldatatest:
    driver: "local"
  redisdata:
    driver: "local"
  psyhistoryroot:
    driver: "local"
  psyhistoryharbor:
    driver: "local"
  nodemodules:
    driver: "local"
  vendor:
    driver: "local"
  composercache:
    external: true
